#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service  # Load-balanced URI через Eureka
#          predicates:
#            - Path=/auth/**  # Все запросы к /auth/** будут перенаправлены в AuthService
#          filters:
#            - StripPrefix=1
##            - RemoveRequestHeader=Cookie  # Убедись, что токен не перезаписывается
#
#        - id: user-service
#          uri: lb://user-service  # Load-balanced URI через Eureka
#          predicates:
#            - Path=/user/**  # Все запросы к /user/** перенаправляются в UserService
#          filters:
#            - StripPrefix=1
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 8080